Form/Flow/CheckFlow.php
<?php

namespace Jiabin\HolterBundle\Form\Flow;

use Jiabin\HolterBundle\Manager\HolterManager;
use Craue\FormFlowBundle\Form\FormFlow;
use Craue\FormFlowBundle\Form\FormFlowInterface;
use Symfony\Component\Form\FormTypeInterface;

class CheckFlow extends FormFlow
{
    /**
     * @var FormTypeInterface
     */
    protected $formType;

    /**
     * @var HolterManager
     */
    protected $manager;

    public function setFormType(FormTypeInterface $formType)
    {
        $this->formType = $formType;
    }

    public function getName()
    {
        return 'check';
    }

    protected function loadStepsConfig()
    {
        return array(
            array(
                'label' => 'base',
                'type' => $this->formType,
            ),
            array(
                'label' => 'options',
                'type' => $this->formType,
                'skip'  => function ($currentStepNumber, $flow) {
                    if ($currentStepNumber > 1) {
                        return $flow->createFormForStep(2)->get('options')->count() === 0;
                    } else {
                        return false;
                    }
                }
            ),
            array(
                'label' => 'confirm',
                'type' => $this->formType
            )
        );
    }

    /**
     * Set manager
     */
    public function setManager(HolterManager $manager)
    {
        $this->manager = $manager;

        return $this;
    }
}

Resources/views/Admin/check.html.twig
{% extends "JiabinHolterBundle:Base:layout.html.twig" %}

{% block subtitle %}admin{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h5 class="panel-title">Admin checks</h5>
                </div>
                {% if checks|length > 0 %}
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Group</th>
                            <th>Engine</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for check in checks %}
                            <tr>
                                <td>
                                    <a href="{{ path('holter_admin_edit_check', {id: check.id}) }}">{{ check.name }}</a>
                                </td>
                                <td>{{ check.displayGroup|default('Default') }}</td>
                                <td>{{ check.engine|replace({"holter.engine.": ""}) }}</td>
                                <td>
                                    <a href="{{ path('holter_admin_edit_check', {id: check.id}) }}" class="btn btn-info btn-sm">
                                        <span class="glyphicon glyphicon-edit"></span>
                                        &nbsp;Edit
                                    </a>
                                    <a href="{{ path('holter_admin_delete_check', {id: check.id}) }}" onclick="return confirm('Are you sure that you want to delete this check?');" class="btn btn-danger btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                        &nbsp;Delete
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <div class="panel-body">You don't have any checks yet!</div>
                {% endif %}
                <div class="panel-footer text-right">
                    <a href="{{ path('holter_admin_new_check') }}" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Add new check</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Resources/views/Admin/check_form.html.twig
{% extends "JiabinHolterBundle:Base:layout.html.twig" %}

{% block subtitle %}admin:check{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-3">
            {% set steps = [{ heading: 'Step 1', text: 'Basic information',
                }, { heading: 'Step 2', text: 'Engine options',
                }, { heading: 'Step 3', text: 'Review & confirmation'}] %}
            <div class="list-group">
                {% for index, step in steps %}
                <a href="#" class="list-group-item {% if flow.getCurrentStepNumber() == index + 1 %}active{% endif %}">
                    <h5 class="list-group-item-heading">{{ step.heading }}</h5>
                    <small class="list-group-item-text">{{ step.text }}</small>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-9">
            <form action="{{ path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) }}" role="form" method="post">
                {{ form_widget(form) }}
                {% if flow.getCurrentStepNumber() == 1 %}
                {% elseif flow.getCurrentStepNumber() == 2 %}
                {% elseif flow.getCurrentStepNumber() == 3 %}
                    {% set check = flow.formData %}
                    <table class="table table-curved table-bordered">
                        <tr>
                            <th scope="row">Name</th>
                            <td>{{ check.name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Engine</th>
                            <td>{{ check.engine }}</td>
                        </tr>
                        {% for key, option in check.options %}
                        <tr>
                            <th scope="row">{{ key|title }}</th>
                            <td>
                                {% if option is null %}
                                    <span class="glyphicon glyphicon-remove"></span>
                                {% else %}
                                    {{ option }}
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                {% endif %}

                {% include 'JiabinHolterBundle:Flow:buttons.html.twig' %}
            </form>
        </div>
    </div>
{% endblock %}

Resources/views/Admin/config.html.twig
{% extends "JiabinHolterBundle:Base:layout.html.twig" %}

{% block subtitle %}admin:config{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <form action="{{ path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) }}" role="form" method="post">
                {{ form_widget(form) }}
                <div class="text-right">
                    <button class="btn btn-primary" type="submit">
                        <span class="glyphicon glyphicon-ok"></span>
                        &nbsp;Save
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

Resources/views/Admin/index.html.twig
{% extends "JiabinHolterBundle:Base:layout.html.twig" %}

{% block subtitle %}admin{% endblock %}

{% block body %}
    <div class="page-header no-border">
        <h5>Admin checks</h5>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default panel-belize">
                {% if checks|length > 0 %}
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Group</th>
                            <th>Engine</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for check in checks %}
                            <tr>
                                <td>
                                    <a href="{{ path('holter_admin_edit_check', {id: check.id}) }}">{{ check.name }}</a>
                                </td>
                                <td>{{ check.displayGroup|default('Default') }}</td>
                                <td>{{ check.engine|replace({"holter.engine.": ""}) }}</td>
                                {# <td>{{ check.createdAt|localizeddate('medium', 'short') }}</td> #}
                                <td>
                                    <a href="{{ path('holter_admin_edit_check', {id: check.id}) }}" class="btn btn-info btn-sm">
                                        <span class="glyphicon glyphicon-edit"></span>
                                        &nbsp;Edit
                                    </a>
                                    <a href="{{ path('holter_admin_delete_check', {id: check.id}) }}" onclick="return confirm('Are you sure that you want to delete this check?');" class="btn btn-danger btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                        &nbsp;Delete
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <div class="panel-body">You don't have any checks yet!</div>
                {% endif %}
                <div class="panel-footer text-right">
                    <a href="{{ path('holter_admin_new_check') }}" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Add new check</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Resources/views/Admin/user.html.twig
{% extends "JiabinHolterBundle:Base:layout.html.twig" %}

{% block subtitle %}admin:user{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h5 class="panel-title">Users list</h5>
                </div>
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Email</th>
                            <th>Name</th>
                            <th>Last login</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ user.email }}</td>
                                <td>{{ user.name }}</td>
                                <td>
                                    {% if user.lastLogin %}
                                        {{ user.lastLogin|localizeddate('short', 'medium') }}
                                    {% else %}
                                        Never
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{{ path('holter_admin_edit_user', {id: user.id}) }}" class="btn btn-info btn-sm">
                                        <span class="glyphicon glyphicon-edit"></span>
                                        &nbsp;Edit
                                    </a>
                                    {% if app.user != user %}
                                    <a href="{{ path('holter_admin_delete_user', {id: user.id}) }}" onclick="return confirm('Are you sure that you want to delete this user?');" class="btn btn-danger btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                        &nbsp;Delete
                                    </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="panel-footer text-right">
                    <a href="{{ path('holter_admin_new_user') }}" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Add new user</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Resources/views/Admin/user_form.html.twig
{% extends "JiabinHolterBundle:Base:layout.html.twig" %}

{% block subtitle %}admin:user{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <form action="{{ path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) }}" role="form" method="post">
                {{ form_widget(form) }}
                <div class="text-right">
                    <button class="btn btn-primary" type="submit">
                        <span class="glyphicon glyphicon-ok"></span>
                        &nbsp;Save
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}